name: Slack + Email notifications

on:
  push:
    branches: ["**"]
  pull_request:
    types: [opened, reopened, synchronize]
  pull_request_review:
    types: [submitted]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Slack: push by sainadh45372
        if: ${{ github.event_name == 'push' && github.event.sender.login == 'sainadh45372' }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          payload=$(printf '{"text":"🟢 *Push* by *%s* to *%s* on branch *%s* \nCompare: %s"}' \
            "${{ github.actor }}" "${{ github.repository }}" "${{ github.ref_name }}" "${{ github.event.compare }}")
          curl -X POST -H 'Content-type: application/json' --data "$payload" "$SLACK_WEBHOOK_URL"

      - name: Slack: PR opened by sainadh45372
        if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' && github.event.pull_request.user.login == 'sainadh45372' }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          payload=$(printf '{"text":"🟣 *Pull Request* opened by *%s*\nRepo: %s\nPR #%s: %s\nURL: %s"}' \
            "${{ github.event.pull_request.user.login }}" \
            "${{ github.repository }}" \
            "${{ github.event.pull_request.number }}" \
            "${{ github.event.pull_request.title }}" \
            "${{ github.event.pull_request.html_url }}")
          curl -X POST -H 'Content-type: application/json' --data "$payload" "$SLACK_WEBHOOK_URL"

      - name: Email when PR approved by sainadh99
        if: ${{ github.event_name == 'pull_request_review' && github.event.review.state == 'approved' && github.event.review.user.login == 'sainadh99' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          secure: false
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "PR #${{ github.event.pull_request.number }} approved by ${{ github.event.review.user.login }}"
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_FROM }}
          body: |
            Repository: ${{ github.repository }}
            Title: ${{ github.event.pull_request.title }}
            URL: ${{ github.event.pull_request.html_url }}
            Approved by: ${{ github.event.review.user.login }}
